name: mirror
on:
  push:
  create:
  delete:
  workflow_dispatch:
jobs:
  mirror-to-gitlab:
    concurrency:
      group: ${{ github.workflow }}-gitlab
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare "https://github.com/$GITHUB_REPOSITORY" .
      - run: git push --mirror "https://x:$GITLAB_TOKEN@gitlab.marylieh.social/md/personal-website/portfolio.git"
        env:
          GITLAB_TOKEN: ${{ secrets.GL_TOKEN }}
